name: gh - GitHub CLI stuff

on:
    push:
        paths:
        - ".github/workflows/tim_gh-stuff.yml"
    workflow_dispatch: # manual

jobs:
    cli:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v4
            - run: env 
            - run: gh --version
            - run: gh auth status
            - run: gh repo list
            - run: gh issue list
            - run: gh workflow list
            - run: gh api /repos/:owner/:repo/actions/workflows
    message:
       runs-on: ubuntu-latest
       steps:
         - name: Print message
           run: node -e "console.log('Hello, world!')"